@extends('layouts.app')

@section('title', 'Cookie Policy | LujanDev')

@section('content')

    <!-- breadcrumb area start -->
    <section class="breadcrumb__area p-relative style-two is-breadcrumb-space">
        <div
            class="breadcrumb__thumb-bg include-bg bg__thumb-position"
            data-background="{{ Vite::asset('resources/imgs/breadcrumb/breadcrumb-bg-12.png') }}"
        ></div>

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-8 col-md-10">
                    <div class="breadcrumb__content-wrapper p-relative z-index-1">
                        <div class="breadcrumb__title-wrapper text-center">
                            <h1 class="breadcrumb__title mb-25">Cookie Policy</h1>

                            <p>
                                Information about cookies and similar technologies used on LujanDev.
                            </p>
                        </div>

                        <div class="breadcrumb__menu text-center">
                            <nav>
                                <ul>
                                    <li>
                                        <span>
                                            <a href="{{ route('home') }}">Home</a>
                                        </span>
                                    </li>
                                    <li>
                                        <span>Cookie Policy</span>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb area end -->

    <!-- cookie content start -->
    <section class="section-space">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-9 col-lg-10">

                    <div class="mb-50">
                        <h3 class="mb-20">1. What are cookies?</h3>

                        <p>
                            Cookies are small files or pieces of information that may be
                            stored on a user's device when visiting a website.
                        </p>

                        <p>
                            They can be used for different purposes, such as enabling
                            essential website functionality, maintaining security,
                            remembering preferences or measuring how a website is used.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">2. Cookies and technologies used by LujanDev</h3>

                        <p>
                            LujanDev uses technical mechanisms that are necessary for
                            the correct operation, security and functionality of the website.
                        </p>

                        <p>
                            These mechanisms may include session and security-related
                            cookies generated by the website infrastructure.
                        </p>

                        <p>
                            The contact form also uses <strong>Cloudflare Turnstile</strong>
                            to help distinguish legitimate visitors from automated traffic
                            and protect the website against spam, bots and abuse.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">3. Strictly necessary cookies</h3>

                        <p>
                            Strictly necessary cookies are used where required to provide
                            essential website functionality, maintain security or support
                            technical processes requested by the user.
                        </p>

                        <p>
                            These cookies do not require consent where their use is strictly
                            necessary for the operation of the website or the provision of
                            a service expressly requested by the user.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">4. Cloudflare Turnstile</h3>

                        <p>
                            LujanDev uses Cloudflare Turnstile on its contact form as a
                            security mechanism designed to detect and prevent automated
                            or malicious activity.
                        </p>

                        <p>
                            When the contact form is used, Cloudflare may process technical
                            information necessary to perform the security verification.
                            Depending on Cloudflare's technical implementation, cookies or
                            similar technologies may be used where necessary for security
                            and fraud prevention purposes.
                        </p>

                        <p>
                            More information about the processing associated with Turnstile
                            is available in the
                            <a href="{{ route('legal.privacy') }}">
                                Privacy Policy
                            </a>.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">5. Analytics cookies</h3>

                        <p>
                            With the user's consent, LujanDev uses
                            <strong>Google Analytics 4 (GA4)</strong>, provided by Google,
                            to understand how visitors use and interact with the website.
                        </p>

                        <p>
                            Google Analytics may collect information such as page views,
                            interactions, approximate geographic location, browser and device
                            information, traffic sources and session-related data.
                        </p>

                        <p>
                            Analytics is not loaded when the user first visits the website.
                            It is only activated after the user selects
                            <strong>Accept</strong> in the cookie consent interface.
                            If the user selects <strong>Reject</strong>, Google Analytics
                            is not loaded.
                        </p>

                        <p>
                            When analytics is accepted, Google Analytics may set first-party
                            cookies including:
                        </p>

                        <ul class="mb-20">
                            <li>
                                <strong>_ga</strong> — used to distinguish users.
                                Default duration: 2 years.
                            </li>
                            <li>
                                <strong>_ga_&lt;container-id&gt;</strong> — used to persist
                                session state. Default duration: 2 years.
                            </li>
                        </ul>

                        <p>
                            Cookie duration may be limited by the user's browser or affected
                            by changes to the analytics configuration.
                        </p>

                        <p>
                            LujanDev does not use Google Analytics for advertising or
                            personalised advertising purposes through this implementation.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">6. Advertising and marketing cookies</h3>

                        <p>
                            LujanDev does not currently use advertising or marketing cookies
                            to create advertising profiles or display personalised advertising.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">7. Managing cookies and consent</h3>

                        <p>
                            When visiting LujanDev for the first time, users can choose
                            whether to accept or reject optional analytics technologies.
                        </p>

                        <p>
                            The user's choice is stored locally in the browser so that
                            LujanDev can remember the selected preference on subsequent visits.
                        </p>

                        <p>
                            Users can change or withdraw their choice at any time by selecting
                            <strong>Cookie Settings</strong> in the website footer.
                        </p>

                        <p>
                            If analytics consent is withdrawn, LujanDev disables further
                            Google Analytics measurement and removes the Google Analytics
                            cookies created by this website where technically possible.
                        </p>

                        <p>
                            Users can also configure their browser to block, restrict or delete
                            cookies stored on their device. Disabling strictly necessary
                            technologies may affect functionality related to forms, security
                            or session management.
                        </p>
                    </div>

                    <div class="mb-50">
                        <h3 class="mb-20">8. Changes to this Cookie Policy</h3>

                        <p>
                            This Cookie Policy may be updated when the technologies,
                            services or third-party providers used by LujanDev change.
                        </p>

                        <p>
                            The date shown below indicates the latest revision of this policy.
                        </p>
                    </div>

                    <div>
                        <p>
                            <small>Last updated: October 2026.</small>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- cookie content end -->

@endsection